name: Deploy to AWS

on:
  push:
    branches:
    - master
    paths:
    - 'tests/**'
    - 'src/**'
    - 'infra/**'
  pull_request:
    branches:
    - master
    paths:
    - 'tests/**'
    - 'src/**'
    - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#noci')"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      working-directory: ./src
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt --target .; fi

    - name: Run Tests
      working-directory: ./src
      run: |
        pip install pytest
        python -m pytest ../tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TERRAFORM_ACCESS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TERRAFORM_ACCESS_SECRET }}

    - name: Build a package
      working-directory: ./src
      run: |
        zip -r9 payload.zip .

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      if: github.event_name == 'pull_request'
      working-directory: ./infra/prod
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      working-directory: ./infra/prod
      id: init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TERRAFORM_ACCESS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TERRAFORM_ACCESS_SECRET }}

    - name: Terraform Validate
      if: github.event_name == 'pull_request'
      working-directory: ./infra/prod
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      working-directory: ./infra/prod
      id: plan
      run: terraform plan -no-color -var="payload=../../src/payload.zip"
      continue-on-error: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TERRAFORM_ACCESS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TERRAFORM_ACCESS_SECRET }}

    - name: Pull Request - Add Plan to PR
      uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style üñå\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ‚öôÔ∏è\`${{ steps.init.outcome }}\`
          #### Terraform Validation ü§ñ${{ steps.validate.outputs.stdout }}
          #### Terraform Plan üìñ\`${{ steps.plan.outcome }}\`
          <details><summary>Show Plan</summary>
          \`\`\`${process.env.PLAN}\`\`\`
          </details>
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
          
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
           repo: context.repo.repo,
           body: output
          })

    - name: Merge - Apply TF
      if: github.event_name == 'push'
      working-directory: ./infra/prod
      id: apply
      run: terraform apply -auto-approve -no-color -var="payload=../../src/payload.zip"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TERRAFORM_ACCESS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TERRAFORM_ACCESS_SECRET }}